hub:
  baseUrl: /iaa/
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      bind_dn_template:
      - uid={username},ou=People,dc=iaa,dc=es
      server_address: dae-ldap.iaa.es
  extraConfig:
    logoConfig: |
      import urllib.request
      urllib.request.urlretrieve("https://drive.google.com/uc?export=download&id=1DH8vbKpTcueOl_druObkmFQSOJlo-8Zd", "iaalogo.png")
      c.JupyterHub.logo_file = '/srv/jupyterhub/iaalogo.png'
proxy:
  secretToken: <YOUR_SECRET_TOKEN>
  service:
    nodePorts:
      http: <YOUR_PORT>
    type: NodePort
singleuser:
  defaultUrl: /lab
  image:
    name: jupyter/minimal-notebook
    pullPolicy: IfNotPresent
    tag: latest
  profileList:
  - default: true
    description: 'To avoid too much bells and whistles: Python.'
    display_name: Minimal environment
  - description: 'If you want the additional bells and whistles: Python, R, and Julia.'
    display_name: Datascience environment
    kubespawner_override:
      image: jupyter/datascience-notebook:latest
  - description: The Jupyter Stacks spark image!
    display_name: Spark environment
    kubespawner_override:
      image: jupyter/all-spark-notebook:latest
  storage:
    dynamic:
      storageClass: local-path
